### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by ed45626** [slazarov/python-bittrex-websocket#13]
I've pulled the latest code and reinstalled -- getting this error (and a cascade of errors after that).  It happens after running for a while, I'm inserting some debug statements in to see where it happens so I can try and catch it.

I am running cfscrape 1.9.1 in python3

If you can shed any light on why or where to look I'll continue testing.

Here's the error log:

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3-1.22-py3.5.egg/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3-1.22-py3.5.egg/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.5/dist-packages/gevent/_socketcommon.py", line 288, in getaddrinfo
    return get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.5/dist-packages/gevent/resolver_thread.py", line 65, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gevent/pool.py", line 325, in apply
    return self.spawn(func, *args, **kwds).get()
  File "/usr/local/lib/python3.5/dist-packages/gevent/event.py", line 385, in get
    return self.get(block=False)
  File "/usr/local/lib/python3.5/dist-packages/gevent/event.py", line 375, in get
    return self._raise_exception()
  File "/usr/local/lib/python3.5/dist-packages/gevent/event.py", line 355, in _raise_exception
    reraise(*self.exc_info)
  File "/usr/local/lib/python3.5/dist-packages/gevent/_compat.py", line 33, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/gevent/threadpool.py", line 211, in _worker
    value = func(*args, **kwargs)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3-1.22-py3.5.egg/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3-1.22-py3.5.egg/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/dist-packages/urllib3-1.22-py3.5.egg/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3-1.22-py3.5.egg/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/urllib3-1.22-py3.5.egg/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fd4003df780>: Failed to establish a new connection: [Errno -2] Name or servi
ce not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests-2.18.4-py3.5.egg/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3-1.22-py3.5.egg/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3-1.22-py3.5.egg/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='socket-beta.bittrex.com', port=443): Max retries exceeded with url: /signalr/negotiate?connectionData=%5B%7B%22name%22%3A+%22coreHub%22%7D%5D&clientProtocol=1.5 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd4003df780>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/bittrex_websocket-0.0.5-py3.5.egg/bittrex_websocket/websocket_client.py", line 287, in _init_connection
    conn.start()
  File "/usr/local/lib/python3.5/dist-packages/signalr/_connection.py", line 47, in start
    negotiate_data = self.__transport.negotiate()
  File "/usr/local/lib/python3.5/dist-packages/signalr/transports/_auto_transport.py", line 16, in negotiate
    negotiate_data = Transport.negotiate(self)
  File "/usr/local/lib/python3.5/dist-packages/signalr/transports/_transport.py", line 26, in negotiate
    negotiate = self._session.get(url)
  File "/usr/local/lib/python3.5/dist-packages/requests-2.18.4-py3.5.egg/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cfscrape-1.9.0-py3.5.egg/cfscrape/__init__.py", line 39, in request
    resp = super(CloudflareScraper, self).request(method, url, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests-2.18.4-py3.5.egg/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests-2.18.4-py3.5.egg/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests-2.18.4-py3.5.egg/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='socket-beta.bittrex.com', port=443): Max retries exceeded with url: /signalr/negotiate?connectionData=%5B%7B%22name%22%3A+%22coreHub%22%7D%5D&clientProtocol=1.5 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd4003df780>: Failed to establish a new connection: [Errno -2] Name or service not known',))


Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/signalr/_connection.py", line 53, in wrapped_listener
    listener()
  File "/usr/local/lib/python3.5/dist-packages/signalr/transports/_ws_transport.py", line 42, in _receive
    for notification in self.ws:
  File "/usr/local/lib/python3.5/dist-packages/websocket/_core.py", line 105, in __iter__
    yield self.recv()
  File "/usr/local/lib/python3.5/dist-packages/websocket/_core.py", line 293, in recv
    opcode, data = self.recv_data()
  File "/usr/local/lib/python3.5/dist-packages/websocket/_core.py", line 310, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/local/lib/python3.5/dist-packages/websocket/_core.py", line 323, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/local/lib/python3.5/dist-packages/websocket/_core.py", line 357, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/local/lib/python3.5/dist-packages/websocket/_abnf.py", line 340, in recv_frame
    self.recv_header()
  File "/usr/local/lib/python3.5/dist-packages/websocket/_abnf.py", line 288, in recv_header
    header = self.recv_strict(2)
  File "/usr/local/lib/python3.5/dist-packages/websocket/_abnf.py", line 375, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/usr/local/lib/python3.5/dist-packages/websocket/_core.py", line 427, in _recv
    return recv(self.sock, bufsize)
  File "/usr/local/lib/python3.5/dist-packages/websocket/_socket.py", line 93, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
Mon Dec 25 19:27:46 2017 <Greenlet at 0x7fd40068df20: wrapped_listener> failed with WebSocketConnectionClosedException

```

**Comment by slazarov** [comment]
Looks like a connection drop to me, then it tries to connect to the backup url `socket-beta.bittrex.com` which is not working and will be removed in the next version.

I am currently working on v0.0.6 which will add reconnection functionality. So far it should be safe for all subscriptions apart from order book sync, so give it a try. Instructions on how to install non-master gits can be found in the README.

Also I suggest running python-bittrex-websocket in a `python2/3.6` `venv` because I can't be sure whether they are any conflicts with other libraries or not.

Also how long does the script run before this occurs? Waiting for you to post back.

**Comment by ed45626** [comment]
Thanks -- I'll v0.0.6 and run that.  It takes about 4 hours for the error to show up, I'll let you know what happens running the new code.

**Comment by ed45626** [comment]
Made a change in _init_connection, it was trying to connect and failing (closing the socket).  I know the internet connection is solid, potentially a slowdown at Bittrex.

I modified the get_url function to cycle through the urls rather than one shot and die.  This takes a list instead of a generator.  I also noticed that conn.wait(20) was too short -- it just kept cycling through.  I opened to 60 and am testing.

>         def get_url(url_list):
>             result = url_list[get_url.counter]
>             get_url.counter += 1
>             if get_url.counter == len(url_list):
>                 get_url.counter = 0
>             return result
>         get_url.counter = 0
>

**Comment by slazarov** [comment]
I will test conn.wait with 60 as well, however, when the connection is active, there is constant stream of data to the debug channel (its muted for the end user) so 20 should be fine. There is a trade off between detecting a dropped connection and killing it with conn.wait thought. 

If you like you can do a pull request to branch 0.0.6 if you get a more efficient solution. The main goals are to detect all exceptions and to create a subscription log so that when a connection fails we can replicate the subscriptions. I will try to push this tomorrow.

**Comment by ed45626** [comment]
I'm going to do a pull request and I'll push -- modified the try-except block to catch everything, and print the error if it falls into the 'catch-all' except clause.

I've been running for a few hours with all tickers from bittrex and it appears stable.  There was one error  but it was from the websocket package (connection already closed) and did not cause the thread to fail.

**Comment by slazarov** [comment]
Closing due to inactivity.
