### ISSUE TITLE
Getting real-time non-stop ticker updates 

### ISSUE THREAD

**Issue by isabellams** [slazarov/python-bittrex-websocket#23]
Hi everyone!
I had a question on how to get real-time non-stop ticker updates using bittrex-websocket library.
Thanks to @slazarov I got this sample, may be useful for others:

`       

        def main():
            class MySocket(BittrexSocket):
                def on_open(self):
                    pass

                def on_ticker_update(self, msg):
                    name = msg['MarketName']
                    print('Just received ticker update for {}.'.format(name))
                    print(msg)

            # Create the socket instance
            ws = MySocket()
            # Enable logging
            ws.enable_log()
            # Define tickers
            tickers = ['BTC-ETH', 'BTC-NEO']
            # Subscribe to ticker information
            ws.subscribe_to_ticker_update(tickers)

            while True:
                sleep(1)

        if __name__ == "__main__":
            main()
`

**Comment by slazarov** [comment]
Lately, I have been getting a lot of messages in my email related to that. 

First of all thanks for all the kind words, they do mean a lot! 

Secondly, going through the readme and the examples is a must. If you have any suggestions for improvements, please say so.

Thirdly, although, I would like to help as much as I can, the questions are more related to general python usage rather than actual issue. I'd prefer to focus what little time I have on actual issues. The rest is commented. I am going to use @isabellams's thread/issue to highlight what's going on exactly within `on_open` and `on_ticker_update` before I create some sort of wiki.

```python
    def main():
        class MySocket(BittrexSocket):
            def on_open(self):
                # Quick and dirty way to create variables within the BittrexSocket class
                # i.e if you create a dict like this self.my_personal_dict = {}
                # you will be able to access it from the main thread (in this case the While True loop below)
                # like this ws.my_personal_dict; of course depending on how you instantiated the BittrexSocket class
                pass

            def on_ticker_update(self, msg):
                # The ticker update channel as per the documentation.
                # People tend to ask me why they are not getting getting quantity/rate/high/low etc
                # This is a basic example so it's up to you to debug the contents of the 'msg' variable
                # and use them as you like
                name = msg['MarketName']
                print('Just received ticker update for {}.'.format(name))
                print(msg)

        # Create the socket instance
        ws = MySocket()
        # Enable logging
        ws.enable_log()
        # Define tickers
        tickers = ['BTC-ETH', 'BTC-NEO']
        # Subscribe to ticker information
        ws.subscribe_to_ticker_update(tickers)

        while True:
            sleep(1)


    if __name__ == "__main__":
        main()
```

**Comment by leo5j472421** [comment]
Hi,
I try to run the example of get_ticker_update 
but here is some problem about the connect with the https://socket-stage.bittrex.com/signalr and https://socket.bittrex.com/signalr here is the message and code , Did I miss something?

```
from __future__ import print_function
from time import sleep
from bittrex_websocket.websocket_client import BittrexSocket


def main():
    class MySocket(BittrexSocket):
        def on_open(self):
            self.ticker_updates_container = {}

        def on_ticker_update(self, msg):
            name = msg['MarketName']
            if name not in self.ticker_updates_container:
                self.ticker_updates_container[name] = msg
                print('Just received ticker update for {}.'.format(name))

    # Create the socket instance
    ws = MySocket()
    ws.on_open()
    # Enable logging
    ws.enable_log()
    # Define tickers
    tickers = ['BTC-ETH', 'BTC-NEO', 'BTC-ZEC', 'ETH-NEO', 'ETH-ZEC']
    # Subscribe to ticker information
    ws.subscribe_to_ticker_update(tickers)

    while len(ws.ticker_updates_container) < len(tickers):
        sleep(1)
    else:
        print('We have received updates for all tickers. Closing...')
        ws.disconnect()

if __name__ == "__main__":
    main()
```

```
2018-01-22 13:24:00 - bittrex_websocket.websocket_client - INFO - [Connection][5b544e6af24248609866802184f5879e]:Trying to establish connection to Bittrex through https://socket-stage.bittrex.com/signalr.
2018-01-22 13:24:05 - bittrex_websocket.websocket_client - ERROR - [Connection][5b544e6af24248609866802184f5879e]:Timeout for url https://socket-stage.bittrex.com/signalr. Please check your internet connection is on.
2018-01-22 13:24:05 - bittrex_websocket.websocket_client - INFO - [Connection][5b544e6af24248609866802184f5879e]:Trying to establish connection to Bittrex through https://socket.bittrex.com/signalr.
2018-01-22 13:24:10 - bittrex_websocket.websocket_client - ERROR - [Connection][5b544e6af24248609866802184f5879e]:Timeout for url https://socket.bittrex.com/signalr. Please check your internet connection is on.
2018-01-22 13:24:10 - bittrex_websocket.websocket_client - ERROR - [Connection][5b544e6af24248609866802184f5879e]:Failed to establish connection through supplied URLS. Leaving to watchdog...
2018-01-22 13:24:20 - bittrex_websocket.websocket_client - ERROR - Failed to subscribe [TickerUpdate][['BTC-ETH', 'BTC-NEO', 'BTC-ZEC', 'ETH-NEO', 'ETH-ZEC']] from connection 5b544e6af24248609866802184f5879e after 20 seconds. The connection is probably down.
```

**Comment by slazarov** [comment]
Your connection is not going through at all. What version are you using? Can you try with [0.0.5.1](https://github.com/slazarov/python-bittrex-websocket/releases/tag/v0.0.5.1) ?


This is what I am getting:
```
2018-01-22 07:45:19 - bittrex_websocket.websocket_client - INFO - [Connection][0633937571b94b03965053eb51b6de3d]:Trying to establish connection to Bittrex through https://socket-stage.bittrex.com/signalr.
2018-01-22 07:45:27 - bittrex_websocket.websocket_client - INFO - [Connection][0633937571b94b03965053eb51b6de3d]:Connection to Bittrex established successfully through https://socket-stage.bittrex.com/signalr
2018-01-22 07:45:27 - bittrex_websocket._auxiliary - INFO - [Subscription][Trades][BTC-ETH]: Enabled.
2018-01-22 07:45:27 - bittrex_websocket._auxiliary - INFO - [Subscription][Trades][BTC-XMR]: Enabled.
[Trades]: BTC-ETH
[Trades]: BTC-ETH
[Trades]: BTC-ETH
[Trades]: BTC-ETH
[Trades]: BTC-ETH
[Trades]: BTC-ETH
```

**Comment by leo5j472421** [comment]
Here is the version information
```
bittrex-websocket==0.0.6.2
cfscrape==1.9.1
Events==0.3
requests==2.18.4
signalr-client==0.0.7
websocket-client==0.46.0
```


here is more problem when I run with version 0.0.5.1 

```
2018-01-22 14:41:09 - bittrex_websocket.websocket_client - INFO - Trying to establish connection to Bittrex through https://socket-stage.bittrex.com/signalr.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\leo5j472421\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cfscrape\__init__.py", line 114, in solve_challenge
    node = execjs.get("Node")
  File "C:\Users\leo5j472421\AppData\Local\Programs\Python\Python35-32\lib\site-packages\execjs\_runtimes.py", line 22, in get
    return _find_runtime_by_name(name)
  File "C:\Users\leo5j472421\AppData\Local\Programs\Python\Python35-32\lib\site-packages\execjs\_runtimes.py", line 61, in _find_runtime_by_name
    "{name} runtime is not available on this system".format(name=runtime.name))
execjs._exceptions.RuntimeUnavailableError: Node.js (V8) runtime is not available on this system

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\leo5j472421\AppData\Local\Programs\Python\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\leo5j472421\AppData\Local\Programs\Python\Python35-32\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\leo5j472421\AppData\Local\Programs\Python\Python35-32\lib\site-packages\bittrex_websocket\websocket_client.py", line 287, in _init_connection
    conn.start()
  File "C:\Users\leo5j472421\AppData\Local\Programs\Python\Python35-32\lib\site-packages\signalr\_connection.py", line 47, in start
    negotiate_data = self.__transport.negotiate()
  File "C:\Users\leo5j472421\AppData\Local\Programs\Python\Python35-32\lib\site-packages\signalr\transports\_auto_transport.py", line 16, in negotiate
    negotiate_data = Transport.negotiate(self)
  File "C:\Users\leo5j472421\AppData\Local\Programs\Python\Python35-32\lib\site-packages\signalr\transports\_transport.py", line 26, in negotiate
    negotiate = self._session.get(url)
  File "C:\Users\leo5j472421\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\leo5j472421\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cfscrape\__init__.py", line 47, in request
    return self.solve_cf_challenge(resp, **kwargs)
  File "C:\Users\leo5j472421\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cfscrape\__init__.py", line 77, in solve_cf_challenge
    params["jschl_answer"] = str(self.solve_challenge(body) + len(domain))
  File "C:\Users\leo5j472421\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cfscrape\__init__.py", line 116, in solve_challenge
    raise EnvironmentError("Missing Node.js runtime. Node is required. Please read the cfscrape"
OSError: Missing Node.js runtime. Node is required. Please read the cfscrape README's Dependencies section: https://github.com/Anorov/cloudflare-scrape#dependencies.
```

**Comment by slazarov** [comment]
Yes, you need node.js. Check Dependencies section in the readme.
