### ISSUE TITLE
Getting gevent.hub.LoopExit exception when trying to combine python-bittrex-websocket with flask multi-threaded

### ISSUE THREAD

**Issue by Celeborn2BeAlive** [slazarov/python-bittrex-websocket#25]
Hi,
First of all thanks for your work on your library.

I'm trying to combine it with flask in order to build a web application connecting to bittrex with python backend and HTML/CSS/JS frontend.

I'm first creating a BittrexSocket with your library, then I'm running flask using "threaded = True" to handle multiple requests to the web server at the same time.  However, when requesting an url (simply http://127.0.0.1:5000/, without any routing), I'm getting the following exception:

gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x2c8d1a01c28 select pending=0 ref=0>)

If I remove the "threaded = True", the exception is not raised anymore. So I think that your library may be touching some shared data also used by flask, in a wrong way. But I'm a newbie to python multi-threaded programming so I can't be sure.

Here is a gist with combining the exemple ticker_updates.py with flask and producing the error: https://gist.github.com/Celeborn2BeAlive/30afcd35f18db4c60484eabcfdcb101e

And a stacktrace for the error:
Exception happened during processing of request from ('127.0.0.1', 51029)
Traceback (most recent call last):
  File "c:\Anaconda3\lib\socketserver.py", line 639, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\Anaconda3\lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\Anaconda3\lib\socketserver.py", line 696, in __init__
    self.handle()
  File "c:\Anaconda3\lib\site-packages\werkzeug\serving.py", line 232, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "c:\Anaconda3\lib\http\server.py", line 418, in handle
    self.handle_one_request()
  File "c:\Anaconda3\lib\site-packages\werkzeug\serving.py", line 263, in handle_one_request
    self.raw_requestline = self.rfile.readline()
  File "c:\Anaconda3\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "c:\Anaconda3\lib\site-packages\gevent\_socket3.py", line 384, in recv_into
    self._wait(self._read_event)
  File "c:\Anaconda3\lib\site-packages\gevent\_socket3.py", line 156, in _wait
    self.hub.wait(watcher)
  File "c:\Anaconda3\lib\site-packages\gevent\hub.py", line 651, in wait
    result = waiter.get()
  File "c:\Anaconda3\lib\site-packages\gevent\hub.py", line 898, in get
    return self.hub.switch()
  File "c:\Anaconda3\lib\site-packages\gevent\hub.py", line 630, in switch
    return RawGreenlet.switch(self)
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x283e3f62b90 select pending=0 ref=0>)

**Comment by slazarov** [comment]
Hi and thanks for the support. I haven't used flask in order to know it's threaded operations work but here is how the socket is organised:

> Main script (Main Thread)
>> BittrexSocket Instance (Sub-thread of Main script)
>>> Connection (Sub-thread of BittrexSocket)

In words: the main scripts spawns a BittrexSocket thread which starts its own connection threads. 

The connection class instantiates a SignalR client which uses gevent. So this is where the conflicts may appear from. However, by simply running your code I don't get any issues like you (output below). I suggest running a code in a new venv for you to be sure that there are any conflicting libraries. Make sure `requests` is installed as `requests[security]` (not saying this is the issue but it might be)

> 2018-01-18 07:38:10 - bittrex_websocket.websocket_client - INFO - [Connection][ef4140a1a1874b05a34d2874c35dd939]:Trying to establish connection to Bittrex through https://socket-stage.bittrex.com/signalr.
> 2018-01-18 07:38:18 - bittrex_websocket.websocket_client - INFO - [Connection][ef4140a1a1874b05a34d2874c35dd939]:Connection to Bittrex established successfully through https://socket-stage.bittrex.com/signalr
> 2018-01-18 07:38:18 - bittrex_websocket._auxiliary - INFO - [Subscription][TickerUpdate][BTC-ETH]: Enabled.
> 2018-01-18 07:38:18 - bittrex_websocket._auxiliary - INFO - [Subscription][TickerUpdate][BTC-NEO]: Enabled.
> 2018-01-18 07:38:18 - bittrex_websocket._auxiliary - INFO - [Subscription][TickerUpdate][BTC-ZEC]: Enabled.
> 2018-01-18 07:38:18 - bittrex_websocket._auxiliary - INFO - [Subscription][TickerUpdate][ETH-NEO]: Enabled.
> 2018-01-18 07:38:18 - bittrex_websocket._auxiliary - INFO - [Subscription][TickerUpdate][ETH-ZEC]: Enabled.
> Just received ticker update for BTC-ETH.
> Just received ticker update for BTC-NEO.
> Just received ticker update for BTC-ZEC.
> Just received ticker update for ETH-ZEC.
> Just received ticker update for ETH-NEO.
>  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

Secondly, I've made the socket to

**Comment by Celeborn2BeAlive** [comment]
Hi, thanks for the answer.
In order to produce the error you have to request an url from your navigator. Flask should then output:

127.0.0.1 - - [18/Jan/2018 13:16:12] "GET / HTTP/1.1" 404 -

and at the same time the exception is thrown.

I've just tried in a new virtual env, making sure requests[security] is the one installed, but the error still occurs. However the server seems to work correctly, I just got the exception each time I send a http request but it does not seem to affect its behavior... Quite strange.

Here is the output of pip freeze in the virtual env:

asn1crypto==0.24.0
bittrex-websocket==0.0.6.1
certifi==2017.11.5
cffi==1.11.4
cfscrape==1.9.1
chardet==3.0.4
click==6.7
cryptography==2.1.4
Events==0.3
Flask==0.12.2
gevent==1.2.2
greenlet==0.4.12
idna==2.6
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.0
pycparser==2.18
PyExecJS==1.5.1
pyOpenSSL==17.5.0
requests==2.18.4
signalr-client==0.0.7
six==1.11.0
sseclient==0.0.18
urllib3==1.22
websocket-client==0.46.0
Werkzeug==0.14.1

**Comment by slazarov** [comment]
Hey @Celeborn2BeAlive, any progress with the issue?

**Comment by slazarov** [comment]
Gevent is no longer required, closing due to inactivity.
