### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by Sile25** [slazarov/python-bittrex-websocket#27]
So i have been trying to use the examples but on every one of them i got this error:
 ``ConnectionError: HTTPSConnectionPool(host='socket-beta.bittrex.com', port=443): Max retries exceeded with url: /signalr/negotiate?connectionData=%5B%7B%22name%22%3A+%22coreHub%22%7D%5D&clientProtocol=1.5 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05A56B70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
`

`

**Comment by slazarov** [comment]
Please update to the newest version. The url is not used anymore.

**Comment by Sile25** [comment]
Thanks, i'm updating it. What is the new url of the Socket?

**Comment by slazarov** [comment]
You can check them from the code, can't copy/paste them right now. Best.

**Comment by leon-presto** [comment]
Didn't work for me either, using "https://socket.bittrex.com/signalr".

2018-01-17 18:12:28 - bittrex_websocket.websocket_client - INFO - [Connection][125669fb89b24b9c8eb9070e7f731a1e]:Trying to establish connection to Bittrex through https://socket.bittrex.com/signalr.
2018-01-17 18:12:48 - bittrex_websocket.websocket_client - ERROR - Failed to subscribe [OrderBook][['BTC-ETH', 'BTC-NEO', 'BTC-ZEC', 'ETH-NEO', 'ETH-ZEC']] from connection 125669fb89b24b9c8eb9070e7f731a1e after 20 seconds. The connection is probably down.
2018-01-17 18:13:05 - bittrex_websocket.websocket_client - ERROR - [Connection][125669fb89b24b9c8eb9070e7f731a1e]:Timeout for url https://socket.bittrex.com/signalr. Please check your internet connection is on.
2018-01-17 18:13:05 - bittrex_websocket.websocket_client - ERROR - [Connection][125669fb89b24b9c8eb9070e7f731a1e]:Failed to establish connection through supplied URLS. Leaving to watchdog...

**Comment by slazarov** [comment]
Can you test using version 0.0.5.x. You can download it from the releases or from Pypi. 

Can you access https://socket.bittrex.com/signalr from your browser?

**Comment by leon-presto** [comment]
Thanks for the answer.
Try v0.0.5.1 and works fine.
What's the difference on that version?

python -m bittrex_websocket.examples.order_book
2018-01-23 14:17:16 - bittrex_websocket.websocket_client - INFO - Trying to establish connection to Bittrex through https://socket-stage.bittrex.com/signalr.
2018-01-23 14:17:25 - bittrex_websocket.websocket_client - INFO - Connection to Bittrex established successfully through https://socket-stage.bittrex.com/signalr.
2018-01-23 14:17:26 - bittrex_websocket._auxiliary - INFO - [Subscription][OrderBook][BTC-ETH]: Enabled.
2018-01-23 14:17:26 - bittrex_websocket._auxiliary - INFO - [Subscription][OrderBook][BTC-NEO]: Enabled.
2018-01-23 14:17:26 - bittrex_websocket._auxiliary - INFO - [Subscription][OrderBook][BTC-ZEC]: Enabled.
2018-01-23 14:17:26 - bittrex_websocket._auxiliary - INFO - [Subscription][OrderBook][ETH-NEO]: Enabled.
2018-01-23 14:17:26 - bittrex_websocket._auxiliary - INFO - [Subscription][OrderBook][ETH-ZEC]: Enabled.
2018-01-23 14:17:26 - bittrex_websocket._auxiliary - INFO - [Subscription][OrderBook][BTC-ETH]: Order book depth set to 10.
2018-01-23 14:17:26 - bittrex_websocket._auxiliary - INFO - [Subscription][OrderBook][BTC-NEO]: Order book depth set to 10.
2018-01-23 14:17:26 - bittrex_websocket._auxiliary - INFO - [Subscription][OrderBook][BTC-ZEC]: Order book depth set to 10.
2018-01-23 14:17:26 - bittrex_websocket._auxiliary - INFO - [Subscription][OrderBook][ETH-NEO]: Order book depth set to 10.
2018-01-23 14:17:26 - bittrex_websocket._auxiliary - INFO - [Subscription][OrderBook][ETH-ZEC]: Order book depth set to 10.
2018-01-23 14:17:30 - bittrex_websocket.websocket_client - INFO - [Subscription][OrderBook][BTC-ETH]: Order book snapshot requested.
2018-01-23 14:17:31 - bittrex_websocket.websocket_client - INFO - [Subscription][OrderBook][BTC-ETH]: Order book snapshot received.
[OrderBook]: BTC-ETH
[OrderBook]: BTC-ETH
[OrderBook]: BTC-ETH
2018-01-23 14:17:33 - bittrex_websocket.websocket_client - INFO - [Subscription][OrderBook][BTC-NEO]: Order book snapshot requested.
2018-01-23 14:17:34 - bittrex_websocket.websocket_client - INFO - [Subscription][OrderBook][BTC-NEO]: Order book snapshot received.
[OrderBook]: BTC-ETH
[OrderBook]: BTC-NEO
2018-01-23 14:17:34 - bittrex_websocket.websocket_client - INFO - [Subscription][OrderBook][BTC-ZEC]: Order book snapshot requested.
2018-01-23 14:17:35 - bittrex_websocket.websocket_client - INFO - [Subscription][OrderBook][BTC-ZEC]: Order book snapshot received.
[OrderBook]: BTC-ETH
[OrderBook]: BTC-ETH

**Comment by slazarov** [comment]
The difference is in how the code handles cookies. I want to isolate the issue however so can you please retry a few times with the latest version again (0.0.6.2), also please post the whole log. Thanks!
  

  
  

  
  
>

**Comment by leon-presto** [comment]
Pull the latest code and test on the master branch and v0.0.6.1 (there is no 0.0.6.2?), both working.
So I have no idea, probably there is something wrong with my environment before.

**Comment by slazarov** [comment]
The latest is 0.0.6.2 both in pypi and the master.
  

  
  

  
  
>

**Comment by Sile25** [comment]
Still not working for me, here is the error log, i updated it

`2018-01-23 10:33:18 - bittrex_websocket.websocket_client - INFO - Trying to establish connection to Bittrex through https://socket-stage.bittrex.com/signalr.
2018-01-23 10:33:18 - bittrex_websocket.websocket_client - INFO - Failed to establish connection through https://socket-stage.bittrex.com/signalr
2018-01-23 10:33:18 - bittrex_websocket.websocket_client - INFO - Trying to establish connection to Bittrex through https://socket.bittrex.com/signalr.
2018-01-23 10:33:18 - bittrex_websocket.websocket_client - INFO - Failed to establish connection through https://socket.bittrex.com/signalr
2018-01-23 10:33:18 - bittrex_websocket.websocket_client - INFO - Trying to establish connection to Bittrex through https://socket-beta.bittrex.com/signalr.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Python27\lib\site-packages\bittrex_websocket\websocket_client.py", line 287, in _init_connection
    conn.start()
  File "C:\Python27\lib\site-packages\signalr\_connection.py", line 47, in start
    negotiate_data = self.__transport.negotiate()
  File "C:\Python27\lib\site-packages\signalr\transports\_auto_transport.py", line 16, in negotiate
    negotiate_data = Transport.negotiate(self)
  File "C:\Python27\lib\site-packages\signalr\transports\_transport.py", line 26, in negotiate
    negotiate = self._session.get(url)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\cfscrape\__init__.py", line 39, in request
    resp = super(CloudflareScraper, self).request(method, url, *args, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='socket-beta.bittrex.com', port=443): Max retries exceeded with url: /signalr/negotiate?connectionData=%5B%7B%22name%22%3A+%22coreHub%22%7D%5D&clientProtocol=1.5 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05DD49D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

`

**Comment by slazarov** [comment]
This is with v0.0.5.x?

**Comment by Sile25** [comment]
Tried again to download the repository a minute ago and run it on python but got the same error

**Comment by DanielAndersen** [comment]
With 0.0.6.2 I'm receiving these errors:

2018-01-23 20:30:58 - bittrex_websocket.websocket_client - INFO - [Connection][647c24dc78944dc3bcd5edf3f80be19a]:Trying to establish connection to Bittrex through https://socket-stage.bittrex.com/signalr.
2018-01-23 20:30:58 - bittrex_websocket.websocket_client - ERROR - [Connection][647c24dc78944dc3bcd5edf3f80be19a]:Failed to establish connection through https://socket-stage.bittrex.com/signalr
2018-01-23 20:30:58 - bittrex_websocket.websocket_client - INFO - [Connection][647c24dc78944dc3bcd5edf3f80be19a]:Trying to establish connection to Bittrex through https://socket.bittrex.com/signalr.
2018-01-23 20:30:58 - bittrex_websocket.websocket_client - ERROR - [Connection][647c24dc78944dc3bcd5edf3f80be19a]:Failed to establish connection through https://socket.bittrex.com/signalr
2018-01-23 20:30:58 - bittrex_websocket.websocket_client - ERROR - [Connection][647c24dc78944dc3bcd5edf3f80be19a]:Failed to establish connection through supplied URLS. Leaving to watchdog...

**Comment by slazarov** [comment]
Hm could be cookie related. I will revert some of the changes to a separate branch for you to test.

**Comment by slazarov** [comment]
Please do and reply back.
`pip install git+https://github.com/slazarov/python-bittrex-websocket.git@0.0.6.2.1`

Also please run the script in a venv because I am not experience that problem and I am connecting successfully.

Also you didn't specify if you get the error immediately or after a certain period.

**Comment by Sile25** [comment]
Tried `pip install git+https://github.com/slazarov/python-bittrex-websocket.git@0.0.6.2.1` and it seems to be working now, thanks!

**Comment by slazarov** [comment]
Keep reporting :).
  

  
  

  
  
>

**Comment by sk123sk** [comment]
Hi, slazarov. I have the same issue .
2018-01-23 20:30:58 - bittrex_websocket.websocket_client - INFO - [Connection][647c24dc78944dc3bcd5edf3f80be19a]:Trying to establish connection to Bittrex through https://socket-stage.bittrex.com/signalr.
2018-01-23 20:30:58 - bittrex_websocket.websocket_client - ERROR - [Connection][647c24dc78944dc3bcd5edf3f80be19a]:Failed to establish connection through https://socket-stage.bittrex.com/signalr
2018-01-23 20:30:58 - bittrex_websocket.websocket_client - INFO - [Connection][647c24dc78944dc3bcd5edf3f80be19a]:Trying to establish connection to Bittrex through https://socket.bittrex.com/signalr.
2018-01-23 20:30:58 - bittrex_websocket.websocket_client - ERROR - [Connection][647c24dc78944dc3bcd5edf3f80be19a]:Failed to establish connection through https://socket.bittrex.com/signalr
2018-01-23 20:30:58 - bittrex_websocket.websocket_client - ERROR - [Connection][647c24dc78944dc3bcd5edf3f80be19a]:Failed to establish connection through supplied URLS. Leaving to watchdog...

I tried pip install git+https://github.com/slazarov/python-bittrex-websocket.git@0.0.6.2.1 (even tried complete uninstall/install python before do that), same problem, nothing changed.

I'm experienced in c++, but 2nd day in Python. I  tried to run your  examples from the folder i cloned from gitHub both by doubleclick and cmd 'cd xxx' 'python.exe order_book.py'

Why can I change?
Thanks in advance!

I

**Comment by slazarov** [comment]
Did you managed to install it through pip? It’s not clear.

**Comment by sk123sk** [comment]
yes, I ran pip install git+https://github.com/slazarov/python-bittrex-websocket.git@0.0.6.2.1  in cmd

**Comment by slazarov** [comment]
The only way for me to replicate this problem is to switch my internet off. This is what I get

> 2018-01-28 00:19:13 - bittrex_websocket.websocket_client - INFO - [Connection][5415beda79ff4f2fa0389882c076834e]:Trying to establish connection to Bittrex through https://socket-stage.bittrex.com/signalr.
> 2018-01-28 00:19:13 - bittrex_websocket.websocket_client - ERROR - [Connection][5415beda79ff4f2fa0389882c076834e]:Timeout for url https://socket-stage.bittrex.com/signalr. Please check your internet connection is on.
> 2018-01-28 00:19:13 - bittrex_websocket.websocket_client - INFO - [Connection][5415beda79ff4f2fa0389882c076834e]:Trying to establish connection to Bittrex through https://socket.bittrex.com/signalr.
> 2018-01-28 00:19:13 - bittrex_websocket.websocket_client - ERROR - [Connection][5415beda79ff4f2fa0389882c076834e]:Timeout for url https://socket.bittrex.com/signalr. Please check your internet connection is on.
> 2018-01-28 00:19:13 - bittrex_websocket.websocket_client - ERROR - [Connection][5415beda79ff4f2fa0389882c076834e]:Failed to establish connection through supplied URLS. Leaving to watchdog...

As you can see the time on the debug error messages doesn't change. In your case it's **2018-01-23 20:30:58** .  On a working connection, it would take 5-8 seconds for the connection to be verified. This is an example log of a working connection:

> 2018-01-28 00:21:20 - bittrex_websocket.websocket_client - INFO - [Connection][3bce7b674c6e4812821e2976cb5853bb]:Trying to establish connection to Bittrex through https://socket-stage.bittrex.com/signalr.
> 2018-01-28 00:21:28 - bittrex_websocket.websocket_client - INFO - [Connection][3bce7b674c6e4812821e2976cb5853bb]:Connection to Bittrex established successfully through https://socket-stage.bittrex.com/signalr
> 2018-01-28 00:21:28 - bittrex_websocket._auxiliary - INFO - [Subscription][OrderBook][ETH-ZEC]: Enabled.
> 2018-01-28 00:21:28 - bittrex_websocket._auxiliary - INFO - [Subscription][OrderBook][ETH-NEO]: Enabled.
> 2018-01-28 00:21:28 - bittrex_websocket._auxiliary - INFO - [Subscription][OrderBook][ETH-ZEC]: Order book depth set to 10.
> 2018-01-28 00:21:28 - bittrex_websocket._auxiliary - INFO - [Subscription][OrderBook][ETH-NEO]: Order book depth set to 10.
> 2018-01-28 00:21:37 - bittrex_websocket.websocket_client - INFO - [Subscription][OrderBook][ETH-ZEC]: Order book snapshot requested.
> 2018-01-28 00:21:37 - bittrex_websocket.websocket_client - INFO - [Subscription][OrderBook][ETH-ZEC]: Order book snapshot received.

See that the first message is from **2018-01-28 00:21:20**  and the second from **2018-01-28 00:21:28**. In your case it doesn't even try to connect.

**Comment by sk123sk** [comment]
I have tried one more time just now. I have this 5+sec delay, while trying to connect. Check cmd screenshot attached below.
![ws_bittr](https://user-images.githubusercontent.com/35844512/35477030-e33383d4-03cb-11e8-8981-057a92a70c6f.jpg)

**Comment by slazarov** [comment]
What is your python version?

**Comment by sk123sk** [comment]
![ws2](https://user-images.githubusercontent.com/35844512/35477060-81155622-03cc-11e8-85bd-55f2fa2df874.jpg)

**Comment by slazarov** [comment]
Can you try using the docker container from:
https://github.com/slazarov/python-bittrex-websocket/tree/0.0.6.2.1/docker

**Comment by sk123sk** [comment]
![ws3](https://user-images.githubusercontent.com/35844512/35477254-5180d676-03d0-11e8-9b9e-0940c1898ec7.jpg)

**Comment by slazarov** [comment]
You have to install docker and then run the dockerfile. It's a software that put's your code in a container that is separated from the rest of your system. In this way we can check if it's  your system that's causing it or something else:

https://www.docker.com/what-docker

**Comment by sk123sk** [comment]
Sorry. Need some help.  
I installed Docker. cd to python-bittrex-websocket-0.0.6.2.1\docker
$docker build -t example .
I can see my new 'example' image now in  "docker images'.
but how to run our bittrex-example after that?
I tried 
$docker run  example  
After that command I can see  our container running here 
$docker container ls 
but no output   -_- nothing..  You help wil be much appreciated.

**Comment by slazarov** [comment]
That’s odd. Can you try with 

> docker container start CONTAINER_ID
Or
> docker container -a start CONTAINER_ID

**Comment by sk123sk** [comment]
![docker](https://user-images.githubusercontent.com/35844512/35486901-f350c064-0485-11e8-9fb4-242ff00869ba.jpg)

no output .

**Comment by slazarov** [comment]
Hey, there is some problem with the docker container. I can't put an ETA yet on it.
Let's try something else, please try installing a `venv`, that's what I am using myself for developing. It isolates a new dev environment from the rest of your installed packages. You can read about how to use it from here:
https://docs.python.org/3/library/venv.html or any other article.

Also try making a Python3 venv.

**Comment by slazarov** [comment]
I've pushed a new update to the master, can you do
`pip install git+https://github.com/slazarov/python-bittrex-websocket.git` and retry, preferable in a `venv`. The version number should be `0.0.6.2.2`

_Note: version 0.0.6.2.1 is for testing_

**Comment by slazarov** [comment]
The docker file from https://github.com/slazarov/python-bittrex-websocket/tree/master/docker should work now.
There are also some other news, the docker container is giving me your error:

> 2018-01-28 23:19:08 - bittrex_websocket.websocket_client - INFO - [Connection][9ebef1448ddf4bcc8a8a0ca2dc372272]:Trying to establish connection to Bittrex through https://socket-stage.bittrex.com/signalr.
> 2018-01-28 23:19:13 - bittrex_websocket.websocket_client - ERROR - [Connection][9ebef1448ddf4bcc8a8a0ca2dc372272]:Timeout for url https://socket-stage.bittrex.com/signalr. Please check your internet connection is on.
> 2018-01-28 23:19:13 - bittrex_websocket.websocket_client - INFO - [Connection][9ebef1448ddf4bcc8a8a0ca2dc372272]:Trying to establish connection to Bittrex through https://socket.bittrex.com/signalr.
> 2018-01-28 23:19:18 - bittrex_websocket.websocket_client - ERROR - [Connection][9ebef1448ddf4bcc8a8a0ca2dc372272]:Timeout for url https://socket.bittrex.com/signalr. Please check your internet connection is on.
> 2018-01-28 23:19:18 - bittrex_websocket.websocket_client - ERROR - [Connection][9ebef1448ddf4bcc8a8a0ca2dc372272]:Failed to establish connection through supplied URLS. Leaving to watchdog...
> 2018-01-28 23:19:28 - bittrex_websocket.websocket_client - ERROR - Failed to subscribe [OrderBook][['BTC-ETH', 'BTC-NEO', 'BTC-ZEC', 'ETH-NEO', 'ETH-ZEC']] from connection 9ebef1448ddf4bcc8a8a0ca2dc372272 after 20 seconds. The connection is probably down.

While if I run it normally, it work ok. Anyways, I am able to replicate the problem now.

**Comment by slazarov** [comment]
Solution found: install https://nodejs.org/en/

**Comment by sk123sk** [comment]
Thank you very much. Not it's working! 
installed https://nodejs.org/en/ and loaded 0.0.6.2.2 version.

**Comment by slazarov** [comment]
Great, read the dependencies section next time ;). Best, Stan. Closing.
