### ISSUE TITLE
I get the following error ( Solved ) 

### ISSUE THREAD

**Issue by ArturoJ** [slazarov/python-bittrex-websocket#45]
2018-03-06 14:34:23 - bittrex_websocket.websocket_client - INFO - [Connection][5ba904306a12492f9346af0e8dca15f9]:Trying to establish connection to Bittrex through https://socket-stage.bittrex.com/signalr.

2018-03-06 14:34:28 - bittrex_websocket.websocket_client - ERROR - [Connection][5ba904306a12492f9346af0e8dca15f9]:Timeout for url https://socket-stage.bittrex.com/signalr. Please check your internet connection is on.

2018-03-06 14:34:28 - bittrex_websocket.websocket_client - INFO - [Connection][5ba904306a12492f9346af0e8dca15f9]:Trying to establish connection to Bittrex through https://socket.bittrex.com/signalr.

2018-03-06 14:34:33 - bittrex_websocket.websocket_client - ERROR - [Connection][5ba904306a12492f9346af0e8dca15f9]:Timeout for url https://socket.bittrex.com/signalr. Please check your internet connection is on.

2018-03-06 14:34:33 - bittrex_websocket.websocket_client - ERROR - [Connection][5ba904306a12492f9346af0e8dca15f9]:Failed to establish connection through supplied URLS. Leaving to watchdog...

2018-03-06 14:34:43 - bittrex_websocket.websocket_client - ERROR - Failed to subscribe [OrderBook][['BTC-ETH']] from connection 5ba904306a12492f9346af0e8dca15f9 after 20 seconds. The connection is probably down.

Traceback (most recent call last):

  File "F:\eclipse\eclipse-workspace\Web_Socket_Python\docker\example.py", line 57, in <module>
    main()

  File "F:\eclipse\eclipse-workspace\Web_Socket_Python\docker\example.py", line 34, in main
    ws.subscribe_to_orderbook(tickers)

  File "F:\eclipse\eclipse-workspace\Web_Socket_Python\bittrex_websocket\websocket_client.py", line 742, in subscribe_to_orderbook
    self.tickers.set_book_depth(tickers, book_depth)

  File "F:\eclipse\eclipse-workspace\Web_Socket_Python\bittrex_websocket\_auxiliary.py", line 153, in set_book_depth
    raise RuntimeError("Unable to set order book depth, timeout")

RuntimeError: Unable to set order book depth, timeout

**Comment by slazarov** [comment]
There is an issue with the socket container. Does it work outside of it?

**Comment by ArturoJ** [comment]
Nothing works, it stops.

**Comment by slazarov** [comment]
I can’t replicte the error because it works on my end so I believe it’s something local. Is nodejs installed? Is requests installed with requests[security]? It’s best to run it in a venv.

**Comment by ArturoJ** [comment]
It works, I was missing the Nodejs. Thank you very much

**Comment by ArturoJ** [comment]
You can increase the depth of the order book is set to 10 to 20?

**Comment by cxxn** [comment]
Hi guys,

My very first post on GitHub, bear with me. 

I've encountered exactly the same errors. I'm relatively new to Python and programming in general so I've been Googling for the past 24 hours. 

I followed all possible solutions given in other issue threads.. I have somehow managed to:

1. Installed various older versions of bittrex-websocket: after installing node, the errors were alike
2. Tried through a virtual machine (venv): also the same errors: no connection
3. Installed Docker after a huge struggle and ran the Dockerfile: also the same errors: no connection

I'm still not quite sure if I've done everything correctly but I'm eager to learn. If I can somehow provide some useful logs, other than stated in this initial topic, let me know!

Kr
cxxn

**Comment by slazarov** [comment]
Hi @cxxn and welcome, follow https://github.com/slazarov/python-bittrex-websocket/wiki/Creating-issues-guideline

Although you might be having the same problems it's not clear what OS is, what other plugins you have installed (e.g potential conflicts). Also the dockerfile was updated yesterday, have you tested it?

**Comment by cxxn** [comment]
Hi @slazarov , thanks for the welcome and I've checked out the guidelines, my bad for not doing this earlier.

1. I'm running on Windows 64-bit.
2. I went for a clean Python install yesterday. I did install some other things that might have been included already but I'm fairly sure I've tested your websocket client before and throughout the installing of these plugins as well, with the same result. 
Here's a result list of command 'pip freeze', I've put items in **bold** of which I'm fairly sure that I manually tried installing as well. Please bear with me for trying a lot of different things.

> asn1crypto==0.24.0
**beautifulsoup4==4.6.0**
**bittrex-websocket==0.0.7.0**
certifi==2018.1.18
cffi==1.11.5
cfscrape==1.9.4
chardet==3.0.4
cryptography==2.1.4
Cython==0.27.3
Events==0.3
gevent==1.3a2
greenlet==0.4.13
idna==2.6
**npm==0.1.1**
oauthlib==2.0.6
odict==1.6.2
optional-django==0.1.0
plumber==1.5
pycparser==2.18
PyExecJS==1.5.1
pyOpenSSL==17.5.0
PySocks==1.6.8
**python-bittrex==0.3.0**
**requests==2.18.4**
requests-oauthlib==0.8.0
signalr-client==0.0.7
six==1.11.0
sseclient==0.0.19
**tweepy==3.6.0
twitter==1.18.0**
urllib3==1.22
websocket-client==0.47.0
wsaccel==0.6.2
zope.component==4.4.1
zope.deprecation==4.3.0
zope.event==4.3.0
zope.interface==4.4.3
zope.lifecycleevent==4.2.0

3. I ran the Docker file 2 hours ago, which should be the latest version.  
4. Error log I'm getting when building in notepad++:

> 2018-03-11 12:45:50 - bittrex_websocket.websocket_client - INFO - [Connection][5aaa076be50d431385e01d8a22e5dc67]:Trying to establish connection to Bittrex through https://socket-stage.bittrex.com/signalr.
2018-03-11 12:45:57 - bittrex_websocket.websocket_client - ERROR - [Connection][5aaa076be50d431385e01d8a22e5dc67]:Timeout for url https://socket-stage.bittrex.com/signalr. Please check your internet connection is on.
2018-03-11 12:45:57 - bittrex_websocket.websocket_client - INFO - [Connection][5aaa076be50d431385e01d8a22e5dc67]:Trying to establish connection to Bittrex through https://socket.bittrex.com/signalr.
2018-03-11 12:46:02 - bittrex_websocket.websocket_client - ERROR - [Connection][5aaa076be50d431385e01d8a22e5dc67]:Timeout for url https://socket.bittrex.com/signalr. Please check your internet connection is on.
2018-03-11 12:46:02 - bittrex_websocket.websocket_client - ERROR - [Connection][5aaa076be50d431385e01d8a22e5dc67]:Failed to establish connection through supplied URLS. Leaving to watchdog...
2018-03-11 12:46:11 - bittrex_websocket.websocket_client - ERROR - Failed to subscribe [OrderBook][['BTC-ETC']] from connection 5aaa076be50d431385e01d8a22e5dc67 after 20 seconds. The connection is probably down.
Traceback (most recent call last):
  File "C:\Users\B\Desktop\bittrex\bittrex.py", line 56, in <module>
    main()
  File "C:\Users\B\Desktop\bittrex\bittrex.py", line 33, in main
    ws.subscribe_to_orderbook(tickers)
  File "C:\Python36\lib\site-packages\bittrex_websocket\websocket_client.py", line 742, in subscribe_to_orderbook
    self.tickers.set_book_depth(tickers, book_depth)
  File "C:\Python36\lib\site-packages\bittrex_websocket\_auxiliary.py", line 153, in set_book_depth
    raise RuntimeError("Unable to set order book depth, timeout")
RuntimeError: Unable to set order book depth, timeout
[Finished in 40.9s]

I did notice that browsing manually to "https://socket.bittrex.com/signalr" results in the standard loading screen of Bittrex for a few seconds and then it shows "Bad Request". 

My apologies for the long post. Which I could give you more relevant information!

Kr,
cxxn

**Comment by slazarov** [comment]
From my experience so far, that error is usually related to missing node (does running node in cmd yield something?) or not installing requests with requests[security]. Can you confirm that?

**Comment by cxxn** [comment]
Running node yields the node command line; node --version shows: v8.10.0 and I can properly use the console.log method as a test.

I read another comment of yours where you suggest installing requests[security]. After reading this I firstly uninstalled requests and then installed requests[security], using pip. 

I have just redone that ("Collecting requests[security]" ... "Successfully installed requests-2.18.4"), restarted PowerShell but I get the same errors.

I've also added PowerShell as an exception to my firewall since I'm starting to think this is a personal issue, but also without success.

Kr,
cxxn

**Comment by slazarov** [comment]
The error you are getting is from, perhaps you can look into that?
> from urllib3.contrib.pyopenssl import SocketError

The problem currently is that I can't find a way to replicate your error and it seems to run fine on my end. Can you try running from a different OS/PC?

**Comment by cxxn** [comment]
Been finding possible solutions for quite some time now. Currently I have no clue where to look! I will repeat this exercise hopefully tomorrow.

It won't be easy to run from a different OS/PC the coming week but I'll see what I can do.

Thanks for your time so far!

cxxn

**Comment by slazarov** [comment]
There might be conflicts with the other libraries you are using.
