### ISSUE TITLE
It works fine, but when compiling I'm not able to make it run ( pyinstaller )

### ISSUE THREAD

**Issue by ArturoJ** [slazarov/python-bittrex-websocket#49]
2018-03-13 09:51:55 - bittrex_websocket.websocket_client - INFO - [Connection]

[161b25740b7045d28881129964a45742]:Trying to establish connection to Bittrex through https://socket-stage.bittrex.com/signalr.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "site-packages\bittrex_websocket\websocket_client.py", line 327, in _init_connection
  File "site-packages\bittrex_websocket\_signalr.py", line 17, in start
  File "site-packages\signalr\transports\_auto_transport.py", line 28, in start
  File "site-packages\signalr\transports\_ws_transport.py", line 38, in start
  File "site-packages\websocket\_core.py", line 494, in create_connection
  File "site-packages\websocket\_core.py", line 217, in connect
  File "site-packages\websocket\_http.py", line 76, in connect
  File "site-packages\websocket\_http.py", line 191, in _ssl_socket
  File "site-packages\websocket\_http.py", line 144, in _wrap_sni_socket
TypeError: cafile, capath and cadata cannot be all omitted

2018-03-13 09:52:15 - bittrex_websocket.websocket_client - ERROR - Failed to subscribe [OrderBook][['BTC-ETH', 'BTC-NEO', 'BTC-ZEC', 'ETH-NEO', 'ETH-ZEC']] from connection 161b25740b7045d28881129964a45742 after 20 seconds. The connection is probably down

**Comment by ArturoJ** [comment]
By the way, thank you very much for sharing this gem.

**Comment by slazarov** [comment]
Hi @ArturoJ, when does it work fine? I haven't used pyinstaller so I can't guarantee its compatible.

**Comment by slazarov** [comment]
Closing due to inactivity.
