### ISSUE TITLE
Entire library not working because cloudflare issue

### ISSUE THREAD

**Issue by davidsander** [slazarov/python-bittrex-websocket#57]
Hello,

Thank you so much for writing this library, it has been immensely useful! Starting very recently, I started getting this issue pasted below. I ran the system on two different machines with different ip's  and also tried to update the cfscrape library. The issue is fatal, causing the entire library to not work.

Please let me know what you think the best fix is:

`Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/gerald/bittrex-ws/bittrex_websocket/bittrex.py", line 200, in run
    self.conn.start()
  File "/home/ubuntu/gerald/bittrex-ws/bittrex_websocket/_signalr.py", line 15, in start
    negotiate_data = self.__transport.negotiate()
  File "/home/ubuntu/gerald/bittrex-ws/env/lib/python3.5/site-packages/signalr/transports/_auto_transport.py", line 16, in negotiate
    negotiate_data = Transport.negotiate(self)
  File "/home/ubuntu/gerald/bittrex-ws/env/lib/python3.5/site-packages/signalr/transports/_transport.py", line 26, in negotiate
    negotiate = self._session.get(url)
  File "/home/ubuntu/gerald/bittrex-ws/env/lib/python3.5/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/home/ubuntu/gerald/bittrex-ws/env/lib/python3.5/site-packages/cfscrape/__init__.py", line 66, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/home/ubuntu/gerald/bittrex-ws/env/lib/python3.5/site-packages/cfscrape/__init__.py", line 97, in solve_cf_challenge
    params["jschl_answer"] = str(self.solve_challenge(body) + len(domain))
  File "/home/ubuntu/gerald/bittrex-ws/env/lib/python3.5/site-packages/cfscrape/__init__.py", line 127, in solve_challenge
    raise ValueError("Error parsing Cloudflare IUAM Javascript challenge. %s" % BUG_REPORT)
ValueError: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.`

**Comment by davidsander** [comment]
Closing because folks at the cf-scrape library are looking into it. https://github.com/Anorov/cloudflare-scrape/issues/145

**Comment by slazarov** [comment]
Are you using the latest version from:
`pip install git+https://github.com/slazarov/python-bittrex-websocket.git`

The socket is working on my side.
